### ISSUE TITLE
Any known threading/GIL issues?

### ISSUE THREAD

**Issue by PallHaraldsson** [cjdoris/PythonCall.jl#108]
Compared to e.g. PyCall, FYI: https://github.com/JuliaPy/PyCall.jl/issues/882

**Comment by cjdoris** [comment]
Not as far as I know. Let me know if you have any specific issues.

**Comment by Moelf** [comment]
so do we drop GIL? One limitation from PyCall is that it doesn't drop GIL, so it's slow when trying to Julia via it as backend of some Python packge

**Comment by cjdoris** [comment]
Yeah calling into Julia from Julia doesn't unlock the GIL. This is because the Julia code could well call back into Python, which would require automatically relocking the GIL, which is all quite complicated and probably slow in general. If you can guarantee your Julia code doesn't call back into Python, you can release the GIL yourself. A future version of JuliaCall will allow something like `some_julia_function.jl_call_nogil(x, y, z)` to make this a bit easier.

**Comment by Moelf** [comment]
>you can release the GIL yourself.

I don't think you can drop GIL from within normal Python

**Comment by cjdoris** [comment]
Sure but you can drop it in the Julia code that you're calling.

**Comment by Moelf** [comment]
how do I do that? "host" is Python, they're using calling Julia function for performance
