### ISSUE TITLE
first import of juliacall clobbers Project.toml

### ISSUE THREAD

**Issue by jlapeyre** [cjdoris/PythonCall.jl#166]
I create a virtual environment in a directory that already contains a `Project.toml` file (it is the toplevel of a Julia package).
Then I do `import juliacall`. (Maybe also `import juliacall.Main`). I may not have had `PythonCall` installed yet. In any case, it was automatically downloaded. But, a new `Project.toml` file was written that contained only the `PythonCall` dependency. This clobbered the existing `Project.toml`.

Suggested improvement: Add `PythonCall` to the existing project. Perhaps with a warning. Or throw an error explaining the conflict.

juliacall 0.8.0

**Comment by cjdoris** [comment]
Project.toml is supposed to be put somewhere private. Do you have `JULIA_PROJECT` set?

**Comment by jlapeyre** [comment]
Yes, I forgot about that. I am using direnv, which sets JULIA_PROJECT.

**Comment by cjdoris** [comment]
I've just pushed a change so that JULIA_PROJECT is now ignored by JuliaPkg. You can use PYTHON_JULIAPKG_PROJECT if you like, but note that the clobbering behaviour you observed is international: JuliaPkg "owns" the project it uses so it can freely add/remove packages without worrying about what the user may have put there.
