### ISSUE TITLE
GC crash when importing pygame & pyjulia

### ISSUE THREAD

**Issue by dpinol** [cjdoris/PythonCall.jl#168]
Hi,
Julia crashes if [pygame](https://github.com/pygame/) is imported after importing julia. The MWE that causes the crash is a python application which just loads pygame after JuliaCall (I get the same crash using [pyjulia](https://github.com/JuliaPy/pyjulia)) and then allocates memory from a Julia thread. Swapping the 2 import lines avoids the issue

```python
from juliacall import Main as jl
import pygame

jl.seval("""
function worker()
        for i in 1:10000000
            a = Float64[]
            push!(a, 0.42)
        end
    end
""")
jl.seval("t= Threads.@spawn worker()")
jl.eval("wait(t)")""")
```
Initially I created a [Julia issue](https://github.com/JuliaLang/julia/issues/45196) but I guess having the issue here is more useful.

**Comment by cjdoris** [comment]
That's weird! Why would loading a module but not using it have that effect? Presumably there is some weird threads thing going on (is pygame multithreaded? I don't know what it is) but I don't know how to diagnose it.

PythonCall/JuliaCall in general doesn't support threads (because of Python's GIL) but I would have thought that using Julia's multithreading to do Julia-only things (i.e. not calling out to Python) would be OK.

Unfortunately I can't reproduce it. Does the same thing happen if you combine those 3 `seval` calls into one? Also I assume the `eval` should be `seval` in the MWE.

**Comment by cjdoris** [comment]
Closing for lack of response. Feel free to reopen.

**Comment by dpinol** [comment]
Hi, since I had a workaround for this issue, I didn't find the time to follow it up. 
I just created #202 for which I don't have a workaround :-( thanks
