### ISSUE TITLE
Would LazyModules.jl apply for your package?

### ISSUE THREAD

**Issue by PallHaraldsson** [cjdoris/PythonCall.jl#171]
Hi,

I did look into most of your dependencies (not all, what I suspected slow), and of those I checked, slowest (while not really slow):

```
julia> @time using CondaPkg
  0.157528 seconds (190.09 k allocations: 15.163 MiB, 36.26% compilation time)
```

still, everything counts and it's not clear to me it's needed at runtime. 

https://discourse.julialang.org/t/ann-accouncing-lazymodules-jl-delay-the-heavy-dependency-loading-to-its-first-use/80890

On first use:
```
julia> @time using PythonCall
    CondaPkg Found dependencies: /home/pharaldsson_sym/.julia/packages/PythonCall/XgP8G/CondaPkg.toml
    CondaPkg Resolving changes
             + python

..

  Install: 24 packages

  Total download: 10MB

──────────────────────────────────────────────────────────────────────────────────────

 31.942154 seconds (5.97 M allocations: 321.197 MiB, 0.93% gc time, 20.66% compilation time)
```

I'm not too concerned with that timing, nor the output since I think it would only appear on first use. Say in production should be completely silent (can you confirm that, i.e. after first use I guess?) and faster:

```
julia> @time using PythonCall
  4.527233 seconds (2.44 M allocations: 137.928 MiB, 1.36% gc time, 84.84% compilation time)
```

while not too fast. If none of the dependencies are the fault, rather some of the code, could you make a similar trick as with LazyModules.jl by copying the concept (or would it be appropriate to move some of your code into a module and just use LazyModules.jl for them? I'm not sure such module[s] need to be external packages or just sub-modules for it to work).

Do you have an idea what slows down most? Some of it could be lazily loaded this way, or even just dropped in my view e.g. matplotlib, e.g. in case that was the problem (I just doubt it's that).

Any idea when 1.0 will be out, i.e. stable API (maybe next version...)?

It seems best you run Python with the "-X utf8" mode, which is new in Python 3.7 (if you don't do it already I suggest it, as a default, at least look into if appropriate, also on Windows, and if bad, if only for Julia->Python): https://peps.python.org/pep-0540/

It's great to see the benchmarks, and with pydel! I did see the "DANGER!" for it in the docs, i.e. for Py_DecRef

PYNULL_CACHE seems clever. Still it seems if you allocate a lot of objects then destroy them they only go to the cache, which seems unlimited, so never deallocated. I'm not sure it's a huge concern, but maybe you want to have a maximum size to it?

You write "about to be unreachable", is that only from the Julia side? Is there a possibility for a pointer to the Py object on the Python side? Could also be a cycle there, will Python take care of that or does Julia's GC take over?

Julia is multi-threaded, and Python is now too (only supported on multi-threaded platforms). Is there any problem calling from a multi-threaded Julia program to Python, or if both sides have threads? I'm not sure if your code is thread-safe. I wasn't sure if Py_DecRef was thread-safe, and tried to find out (that page might be outdated):

https://www.caichinger.com/blog/2015/05/23/python_atomic_refcounting_slowdown/

I was going to compare the speed from the other side, but FYI:
```
$ python3.6

>>> from juliacall import Main as jl
Querying Julia versions from https://julialang-s3.julialang.org/bin/versions.json
Found Julia 1.6.0-DEV at 'julia' (but looking for Julia 1.7.2)
..
Installing Julia 1.7.2 to /home/pharaldsson_sym/.julia/pythoncall/julia-1.7.2
ERROR: LoadError: ArgumentError: Package Tables does not have OrderedCollections in its dependencies:
- If you have Tables checked out for development and have
  added OrderedCollections as a dependency but haven't updated your primary
  environment's manifest file, try `Pkg.resolve()`.
```

**Comment by cjdoris** [comment]
CondaPkg is always required by PythonCall - it is used in `__init__()` to ensure that Python is installed. None of the packages are very slow to import, it's PythonCall itself which is slow to import, so I don't think something like LazyModules will help.

I'm not sure what makes PythonCall slow to import, but I don't think it's things like the matplotlib helpers. I think it's partly that there are some `@cfunction`s to compile, and this happens every time the module is loaded. But I'm not really sure. Personally I don't find 5 seconds much of a wait, so it's low priority for me, unless there are easy things to fix.

The `PYNULL_CACHE` only contains as many Python objects as have ever existed at the same time in the session, which means that the **peak** memory usage is not affected. It may use more memory at off-peak times, but never more than the peak.

The reachability thing is a bit complicated. It's referring to the Julia object, not the Python object. Take for example:
```julia
x = pylist([3])
y = x[0]
z = x[0]
```
Then `y` and `z` are different Julia objects (i.e. `y === z` returns `false`) but they represent the same Python object (i.e. `pyis(y, z)` returns `true`). If `y` goes out of scope and nothing else holds a reference to it, then the garbage collector is free to deallocate it. If this is the case, then it is legal to call `pydel!(y)` first to put it in the cache. It doesn't matter that `z` still exists and holds a reference to the same Python object. On the other hand, if you did this:
```julia
x = pylist([3])
y = x[0]
z = y
```
then now `y` and `z` are the same Julia object (`y===z` is `true`) so you can't do `pydel!(y)` if only `y` goes out of scope because `z` is the same Julia object and is still in scope.

You can't call between Python and Julia from different threads, this will definitely break at the moment.
