### ISSUE TITLE
Error when using PythonCall attached to a previous Conda environment.

### ISSUE THREAD

**Issue by martinmestre** [cjdoris/PythonCall.jl#224]
Hello,
I would be very gratefull to understand what is the problem. I followed the instructions:
```
julia > ENV["JULIA_CONDAPKG_BACKEND"] = "System"
julia > ENV["JULIA_CONDAPKG_EXE"] = "/home/mmestre/.conda/envs/cosmos/bin/python3.9"
```

Then I install PythonCall.
```
(RiosDelCosmos) pkg> st
      Status `~/casa/work/2022/RiosDelCosmos/Project.toml`
  [6099a3de] PythonCall v0.9.6
```

When I try to use it I get an error (I do have astropy installed in the cosmos environment):

```
julia> using PythonCall
julia> ast = pyimport("astropy")
ERROR: Python: ModuleNotFoundError: No module named 'astropy'
Python stacktrace: none
Stacktrace:
 [1] pythrow()
   @ PythonCall ~/.julia/packages/PythonCall/DqZCE/src/err.jl:94
 [2] errcheck
   @ ~/.julia/packages/PythonCall/DqZCE/src/err.jl:10 [inlined]
 [3] pyimport(m::String)
   @ PythonCall ~/.julia/packages/PythonCall/DqZCE/src/concrete/import.jl:11
 [4] top-level scope
   @ REPL[5]:1

```
I also tried with 
`julia > ENV["JULIA_CONDAPKG_EXE"] = "/home/mmestre/.conda/envs/cosmos/bin/python"`
obtaining the same result.
Thank you very much in advance.

**Comment by cjdoris** [comment]
See here: https://cjdoris.github.io/PythonCall.jl/stable/pythoncall/#If-you-don't-want-to-use-Conda

I think you just need
```julia
ENV["JULIA_PYTHONCALL_EXE"] = "/home/mmestre/.conda/envs/cosmos/bin/python3.9"
```

You must also ensure your Conda environment is activated before starting Julia, since CondaPkg is not used if you specify the python executable.

**Comment by martinmestre** [comment]
Thanks @cjdoris. This commands:
```
julia > ENV["JULIA_CONDAPKG_BACKEND"] = "System"
julia > ENV["JULIA_CONDAPKG_EXE"] = "/home/mmestre/.conda/envs/cosmos/bin/python3.9"
julia > ENV["JULIA_PYTHONCALL_EXE"] = "/home/mmestre/.conda/envs/cosmos/bin/python3.9"
```
must be applied once before installing PythonCall, or each time I run Julia?

**Comment by martinmestre** [comment]
Hello @cjdoris, I do not understand why your command
`ENV["JULIA_PYTHONCALL_EXE"] = "/home/mmestre/.conda/envs/cosmos/bin/python3.9"`
worked, because according to the tutorial, that env variable must be set when one doesn't want to use conda.
And I want to use conda. In fact I want to use my conda environment.

Alternatively I also tried to use CondaPkg but I have a Python packages that is installed like [this](https://github.com/cmateu/galstreams) and it gave me errors.

**Comment by cjdoris** [comment]
OK, maybe the wording of those instructions could be made clearer: by "use Conda" I really mean "use CondaPkg to automatically create a new Conda environment with all your dependencies", which is not what you want, since you want to re-use an existing environment.

By setting `JULIA_PYTHONCALL_EXE`, you tell PythonCall exactly which Python executable you'd like to use (it doesn't matter whether or not it was installed by Conda) and PythonCall will not use CondaPkg and so will not install any Conda packages for you. So it is up to you to ensure all your Python dependencies are already installed.

It should not be necessary to set any other environment variables if you are only using PythonCall, but you can also set `JULIA_CONDAPKG_BACKEND=Null` to completely prevent CondaPkg from installing anything. You do not need to set `JULIA_CONDAPKG_EXE` at all (and in your example it was wrong, since it is meant to be a Conda executable, not Python).

These env vars need to be set every session. To do this automatically you can do this in your `startup.jl` file, or put them into the init file of whichever shell you use.

**Comment by martinmestre** [comment]
Thanks! Ok, so I think I have understood almost everything. I have been able to use PythonCall with a previous conda env by setting only: `JULIA_PYTHONCALL_EXE`.
For completeness, only remains to know in which case I should set  
`JULIA_CONDAPKG_EXE`.
Thank you very much again.

**Comment by cjdoris** [comment]
I've reworded the docs a bit, I'd be grateful if you could read and tell me if they are clearer: https://cjdoris.github.io/PythonCall.jl/dev/pythoncall/#pythoncall-config

**Comment by martinmestre** [comment]
Thanks, of course I will read it. 
I think it is clearer now. Just to confirm I understood correctly. If I want to use a conda environment similar to a preexisting one, and be able to add further packages, then I should use CondaPkg with:
```
ENV["JULIA_CONDAPKG_BACKEND"] = "Current"
ENV["JULIA_CONDAPKG_EXE"] = "/path/to/conda"  # optional
```
Right?

**Comment by cjdoris** [comment]
Yes, the `Current` backend will allow CondaPkg to install things into whatever Conda environment is currently active. It's a new backend (I added it today) and has not been released yet.

**Comment by martinmestre** [comment]
Thank you a lot! issue closed!
