### ISSUE TITLE
`isvalid` error with PythonCall.Utils.StaticString

### ISSUE THREAD

**Issue by CarloLucibello** [cjdoris/PythonCall.jl#254]
When converting to `PyArray` some numpy arrays with string elements, I end up with strings of type `PythonCall.Utils.StaticString{UInt32, 44}`.

It seems that this type is not well supported though, and I get the following errors when indexing and computing the length:
```julia
julia> s = PythonCall.Utils.StaticString{UInt32, 44}("ababababb")
"ababababb"

julia> s[1]
ERROR: MethodError: no method matching isvalid(::PythonCall.Utils.StaticString{UInt32, 44}, ::Int64)
Closest candidates are:
  isvalid(::AbstractString, ::Integer) at strings/basic.jl:143
  isvalid(::SubstitutionString, ::Integer) at regex.jl:566
  isvalid(::Type{T}, ::Integer) where T<:AbstractChar at strings/unicode.jl:58
  ...
Stacktrace:
 [1] isvalid
   @ ./strings/basic.jl:143 [inlined]
 [2] getindex(s::PythonCall.Utils.StaticString{UInt32, 44}, i::Int64)
   @ Base ./strings/basic.jl:186
 [3] top-level scope
   @ REPL[5]:1

julia> length(s)
ERROR: MethodError: no method matching isvalid(::PythonCall.Utils.StaticString{UInt32, 44}, ::Int64)
Closest candidates are:
  isvalid(::AbstractString, ::Integer) at strings/basic.jl:143
  isvalid(::SubstitutionString, ::Integer) at regex.jl:566
  isvalid(::Type{T}, ::Integer) where T<:AbstractChar at strings/unicode.jl:58
  ...
Stacktrace:
 [1] isvalid
   @ ./strings/basic.jl:143 [inlined]
 [2] length
   @ ./strings/basic.jl:396 [inlined]
 [3] length(s::PythonCall.Utils.StaticString{UInt32, 44})
   @ Base ./strings/basic.jl:387
 [4] top-level scope
   @ REPL[6]:1

julia> s isa AbstractString # in principle the type should implement the whole interface
true
```

**Comment by cjdoris** [comment]
Yeah, `PythonCall.Utils.StaticString` is pretty minimal in what it supports - you can convert them to `String` but not much else.

Supporting indexing is harder because it requires understanding UTF-8 and UTF-32 - AFAIK Julia doesn't provide much support for implementing your own string types in terms of handling the encoding (even UTF-8) except for the `transcode` function, which I use to convert to `String`.

If you are getting these from a `PyArray`, I have just pushed a change to the main branch so that you can do `PyArray{String}(x)` on a Python array of strings, which converts the elements to `String` when you access them. Of course this is slower than accessing them as `PythonCall.Util.StaticString` but if you need indexing then it's an option.

**Comment by CarloLucibello** [comment]
I see you have implemented indexing in the last commits, thanks, the examples in the OP now work:
```julia
julia> s = PythonCall.Utils.StaticString{UInt32, 44}("ababababb")
"ababababb"

julia> s[1]
'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)

julia> length(s)
9

julia> s[1:2]
"ab"

julia> s[1:2] |> typeof
SubString{PythonCall.Utils.StaticString{UInt32, 44}}
```
Can we get a new release?

**Comment by cjdoris** [comment]
I decided it wasn't so hard! Sure I'll make a release this week.

**Comment by CarloLucibello** [comment]
Hi, sorry to bother but it would be great to have a new release!

**Comment by cjdoris** [comment]
Sure - done.
