### ISSUE TITLE
Unable to precompile when importing a locally defined module

### ISSUE THREAD

**Issue by josephsdavid** [cjdoris/PythonCall.jl#281]
Hello! I am having a very hard time importing a local module. I have tried how it is demoed in #70, but i am having little to no luck. I have made a demo with a small MRE for what i am trying to do [here](https://github.com/josephsdavid/pythoncallmre.jl). Is there something i am doing wrong? Or what is the Blessed way to import a local module these days?

(Note, it works just fine when I am running it line by line, but when I "using" the Julia module nothing seems to work)

**Comment by cjdoris** [comment]
It would be useful in the future if you include the error you are seeing too.

I assume you're getting
```
ERROR: InitError: Python: ModuleNotFoundError: No module named 'foo'
```
which occurs because the line https://github.com/josephsdavid/pythoncallmre.jl/blob/main/src/pythoncallmre.jl#L8 should be
```julia
pth = (@__DIR__) * "/../py"
```
because `@__DIR__` is the `src` directory.

Aside, it's better to do
```julia
pth = joinpath(dirname(@__DIR__), "py")
```
which is platform-independent.

**Comment by josephsdavid** [comment]
🤦 ah whoops, thank you so much for your help on this :)
