### ISSUE TITLE
jl.pytruth(np.bool_(False)) == true

### ISSUE THREAD

**Issue by schlichtanders** [cjdoris/PythonCall.jl#321]
**Affects:** Both

**Describe the bug**
A clear and concise description of what the bug is. What did you expect? What happened instead?

numpy has its own boolean values [see its docs](https://numpy.org/doc/stable/reference/arrays.scalars.html#numpy.bool_).
Using python, the numpy bools look exactly like normal bools, but are different types.

When using PythonCall/JuliaCall unfortunately numpy bools behaviour entirely differently from normal Python bool. That is very confusing. Especially
```julia
from juliacall import Main as jl
jl.pytruth(np.bool_(False))  # returns true
```

I guess this is just a bug with pytruth which actually should return `true` in this case.

**Your system**
Please provide detailed information about your system:
- The operating system: Nixos
- Julia 1.9.0 PythonCall/JuliaCall 0.9.13

**Comment by cjdoris** [comment]
Are you sure you're on 0.9.13? This look a lot like an issue that was solved in 0.9.13, and I can't reproduce it:
```python
>>> from juliacall import Main as jl
>>> import numpy as np
>>> jl.pytruth(np.bool_(False))
False
>>> jl.pytruth(np.bool_(True))
True
```

Also, what's the actual issue you're having? Because it never really makes sense to do `jl.pytruth(x)` from Python when you can do `bool(x)` instead.

**Comment by schlichtanders** [comment]
yes I can confirm I am on 0.9.13

![image](https://github.com/cjdoris/PythonCall.jl/assets/4255480/1084cba9-03cd-4ed3-bcb1-498738cf6f8d)

In the same vscode notebook `jl.pytruth(np.bool_(False))` returns true

**Comment by schlichtanders** [comment]
My usecase is that I am compiling a super small intro to PythonCall which is going to be presented today evening,  where by chance I run into this point.

**Comment by cjdoris** [comment]
I really can't see how you can get this issue on the current version. Are you definitely not on a dev version of PythonCall? What are `juliacall.__version__`, `juliapkg.status()`, `juliapkg.state.STATE` and `pip show juliacall`?

Also, when I asked about your usecase, I more meant in terms of code. Like I said, doing `jl.pytruth(anything)` is weird because you can do `bool(anything)` instead. Are you actually using `pytruth` from within a Julia function? If so, you should wrap that function using [`jl.pyfunc`](https://cjdoris.github.io/PythonCall.jl/stable/pythoncall-reference/#PythonCall.pyfunc) to create a Python callback function which avoids the automatic conversion causing the issues you're having.

**Comment by schlichtanders** [comment]
thank you so much for not giving up!! Everything works now.

indeed the python kernel I used was not the one I thought I would be using. So I got 0.9.12 there for juliacall.__version__

and yes indeed I was originally using `pytruth` on the julia side of things, but running a python kernel using the python way was better for sharing here on github.
